//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsprojCleaner.App.WindowsForms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsprojCleaner.App.WindowsForms.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Projects!.
        /// </summary>
        internal static string CleanProjects {
            get {
                return ResourceManager.GetString("CleanProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Check log for more information..
        /// </summary>
        internal static string ErrorExceptionVerifyLog {
            get {
                return ResourceManager.GetString("ErrorExceptionVerifyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error (ReadFolderException). Check log for more information..
        /// </summary>
        internal static string ErrorFolderExceptionVerifyLog {
            get {
                return ResourceManager.GetString("ErrorFolderExceptionVerifyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falied to load or create error log:.
        /// </summary>
        internal static string ErrorLogExceptionInitialize {
            get {
                return ResourceManager.GetString("ErrorLogExceptionInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished! Click to run again..
        /// </summary>
        internal static string FinishedClickToRunAgain {
            get {
                return ResourceManager.GetString("FinishedClickToRunAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify if all directories are filled..
        /// </summary>
        internal static string VerifyIfAllDirsAreFilled {
            get {
                return ResourceManager.GetString("VerifyIfAllDirsAreFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
